### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by JXUnx1** [amjadbouhouch/rn-text-editor#3]
I am a native developer, but as I have just learned React Native, I am not very good at it
This library is the only better rich text editor I have found, but currently it has too few features and only supports bolding, tilting, and highlighting. May I ask if it is possible to add more features?

**Comment by amjadbouhouch** [comment]
Thank you for your feedback and I appreciate your interest.

At this stage, the library is still in `beta and not stable 🚫`, and there is a lot of work that needs to be done, which is why the feature set is somewhat limited.

I created this library to explore the possibility of native support for rich text in React Native. Although I don't have plans to add more features, the library is fully extensible.

**Comment by JXUnx1** [comment]
I'm sorry to hear this news
This library is really great, and I am currently exploring how to use it. Even without adding more features, it is still a great implementation method
wish you good luck
